// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRz5-Lvpnsgl7t8Auy6HA9ALdHyQA6joc',
    appId: '1:724731256016:web:49e419642f6eb66b5bd2d5',
    messagingSenderId: '724731256016',
    projectId: 'currency-converter-app-e51a6',
    authDomain: 'currency-converter-app-e51a6.firebaseapp.com',
    storageBucket: 'currency-converter-app-e51a6.appspot.com',
    measurementId: 'G-LX1HKV4L7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeAWq5UXUM3FXYZd17v1KQd6RNHuaX1nI',
    appId: '1:724731256016:android:0129010de01dd2d35bd2d5',
    messagingSenderId: '724731256016',
    projectId: 'currency-converter-app-e51a6',
    storageBucket: 'currency-converter-app-e51a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC25qsxJwqAmkLb6eYfsAOcTO9Y1DSDn68',
    appId: '1:724731256016:ios:d8ff2dd343d3939a5bd2d5',
    messagingSenderId: '724731256016',
    projectId: 'currency-converter-app-e51a6',
    storageBucket: 'currency-converter-app-e51a6.appspot.com',
    iosBundleId: 'com.example.currencyConverterApp',
  );
}
